---
- name: enable HA-all policy
  hosts: app1server
  gather_facts: true
  tags: [rabbit]

  tasks:
    - name: stop rabbitmq app
      command: rabbitmqctl stop_app
      register: cluster_master
    
    - name: start rabbitmq app
      command: rabbitmqctl start_app
      register: cluster_master    


    - name: rabbitmq clustering set_policy ha-all
      command: rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'

    - name: enable mgmt console
      command: rabbitmq-plugins enable rabbitmq_management 
